version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - ./mongo:/data/db
        container_name: "docker-mongodb"
        env_file:
            - .env
    mongo-express:
        image: mongo-express
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
        volumes:
            - ./mongo/${MONGO_VOLUME}:/var/lib/mongo/data/mongodata
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
        depends_on:
            - mongodb